"""empty message

Revision ID: 15f18e50ecbe
Revises: 157721907cb0
Create Date: 2024-04-21 16:45:02.593813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15f18e50ecbe'
down_revision = '157721907cb0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questionnaires',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=False),
    sa.Column('burner_email', sa.String(length=50), nullable=False),
    sa.Column('campers', sa.String(length=100), nullable=False),
    sa.Column('space_required', sa.String(length=100), nullable=False),
    sa.Column('leader_question', sa.String(length=50), nullable=False),
    sa.Column('camp_donation', sa.String(length=50), nullable=False),
    sa.Column('early_arrival', sa.String(length=50), nullable=False),
    sa.Column('why_go', sa.String(length=5000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('questionnaire')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questionnaire',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('full_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('burner_email', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('campers', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('space_required', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('leader_question', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('camp_donation', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('early_arrival', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('why_go', sa.VARCHAR(length=5000), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='questionnaire_pkey')
    )
    op.drop_table('questionnaires')
    # ### end Alembic commands ###
