"""empty message

Revision ID: 9614d4e14c04
Revises: 
Create Date: 2024-05-21 19:35:42.369181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9614d4e14c04'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questionnaires',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=False),
    sa.Column('burner_email', sa.String(length=50), nullable=False),
    sa.Column('campers', sa.String(length=100), nullable=False),
    sa.Column('space_required', sa.String(length=100), nullable=False),
    sa.Column('leader_question', sa.String(length=50), nullable=False),
    sa.Column('camp_donation', sa.String(length=50), nullable=False),
    sa.Column('early_arrival', sa.String(length=50), nullable=False),
    sa.Column('why_go', sa.String(length=5000), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('questionnaires')
    # ### end Alembic commands ###
