"""empty message

Revision ID: af207ad5e7ba
Revises: ce9afb34b0d4
Create Date: 2024-04-11 18:17:51.958571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af207ad5e7ba'
down_revision = 'ce9afb34b0d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questionnaire', schema=None) as batch_op:
        batch_op.drop_constraint('questionnaire_burner_email_key', type_='unique')
        batch_op.drop_constraint('questionnaire_camp_donation_key', type_='unique')
        batch_op.drop_constraint('questionnaire_campers_key', type_='unique')
        batch_op.drop_constraint('questionnaire_early_arrival_key', type_='unique')
        batch_op.drop_constraint('questionnaire_full_name_key', type_='unique')
        batch_op.drop_constraint('questionnaire_leader_question_key', type_='unique')
        batch_op.drop_constraint('questionnaire_phone_number_key', type_='unique')
        batch_op.drop_constraint('questionnaire_space_required_key', type_='unique')
        batch_op.drop_constraint('questionnaire_why_go_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questionnaire', schema=None) as batch_op:
        batch_op.create_unique_constraint('questionnaire_why_go_key', ['why_go'])
        batch_op.create_unique_constraint('questionnaire_space_required_key', ['space_required'])
        batch_op.create_unique_constraint('questionnaire_phone_number_key', ['phone_number'])
        batch_op.create_unique_constraint('questionnaire_leader_question_key', ['leader_question'])
        batch_op.create_unique_constraint('questionnaire_full_name_key', ['full_name'])
        batch_op.create_unique_constraint('questionnaire_early_arrival_key', ['early_arrival'])
        batch_op.create_unique_constraint('questionnaire_campers_key', ['campers'])
        batch_op.create_unique_constraint('questionnaire_camp_donation_key', ['camp_donation'])
        batch_op.create_unique_constraint('questionnaire_burner_email_key', ['burner_email'])

    # ### end Alembic commands ###
