"""empty message

Revision ID: ca1b0c5a4fb1
Revises: af207ad5e7ba
Create Date: 2024-04-11 21:36:28.260723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca1b0c5a4fb1'
down_revision = 'af207ad5e7ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questionnaire', schema=None) as batch_op:
        batch_op.alter_column('why_go',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=5000),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('questionnaire', schema=None) as batch_op:
        batch_op.alter_column('why_go',
               existing_type=sa.String(length=5000),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)

    # ### end Alembic commands ###
