"""empty message

Revision ID: ce9afb34b0d4
Revises: 7bf204de3ea5
Create Date: 2024-04-06 16:44:34.833323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce9afb34b0d4'
down_revision = '7bf204de3ea5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questionnaire',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=50), nullable=False),
    sa.Column('phone_number', sa.String(length=50), nullable=False),
    sa.Column('burner_email', sa.String(length=50), nullable=False),
    sa.Column('campers', sa.String(length=100), nullable=False),
    sa.Column('space_required', sa.String(length=100), nullable=False),
    sa.Column('leader_question', sa.String(length=50), nullable=False),
    sa.Column('camp_donation', sa.String(length=50), nullable=False),
    sa.Column('early_arrival', sa.String(length=50), nullable=False),
    sa.Column('why_go', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('burner_email'),
    sa.UniqueConstraint('camp_donation'),
    sa.UniqueConstraint('campers'),
    sa.UniqueConstraint('early_arrival'),
    sa.UniqueConstraint('full_name'),
    sa.UniqueConstraint('leader_question'),
    sa.UniqueConstraint('phone_number'),
    sa.UniqueConstraint('space_required'),
    sa.UniqueConstraint('why_go')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questionnaire')
    # ### end Alembic commands ###
